---
- name: Play for setting up windows 
  hosts: windows

  vars_files:
    - ./vars/ad_user_vars.yml
    - ./vars/ssh_var.yml     
  roles:
    - win_ad_install
    - win_ad_user
    - win_service_config
